version: "3.9"

services:
  database:
    image: postgres
    container_name: rentx-api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=rentxpg
      - POSTGRES_PASSWORD=rentxpg
      - POSTGRES_DB=rentx_db
